#!/usr/bin/env python3
"""Draw the dashboard page background SVG from the "background" block of showcase/dashboard.json.

Run from the repo root:

    py tools/showcase/make_background.py              # writes showcase/theme/<page.background>
    py tools/showcase/make_background.py --repo <path>

Standard library only, deterministic. It draws the navy band with its shallow curved bottom edge
(the KPI cards straddle it), the two thin dividers in the band, the vertical dividers of the lower
grid and the footer band. build_showcase.py then registers the file and sets it as the page
background. Words, the logo and the visuals are not part of the image.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def num(v) -> str:
    v = float(v)
    return str(int(v)) if v.is_integer() else f"{v:g}"


def stops(pairs) -> list[str]:
    return [f'    <stop offset="{num(o)}" stop-color="{c}"/>' for o, c in pairs]


def render(layout: dict) -> str:
    page = layout["page"]
    w, h = int(page["width"]), int(page["height"])
    bg = layout["background"]
    band = bg["band"]
    edge, centre = float(band["edgeY"]), float(band["centerY"])
    # A quadratic curve peaks halfway between its end points and its control point.
    ctrl = 2 * centre - edge
    band_path = f"M0 0 H{w} V{num(edge)} Q{num(w / 2)} {num(ctrl)} 0 {num(edge)} Z"
    out = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="0 0 {w} {h}">',
        "<!-- Generated by tools/showcase/make_background.py from showcase/dashboard.json. Edit that file, not this one. -->",
        "<defs>",
        '  <linearGradient id="band" x1="0" y1="1" x2="1" y2="0">',
        *stops(band["stops"]),
        "  </linearGradient>",
        '  <linearGradient id="sheen" x1="0" y1="0" x2="0" y2="1">',
        f'    <stop offset="0" stop-color="#FFFFFF" stop-opacity="{num(band.get("sheenOpacity", 0))}"/>',
        '    <stop offset="1" stop-color="#FFFFFF" stop-opacity="0"/>',
        "  </linearGradient>",
    ]
    footer = bg.get("footer")
    if footer:
        out += ['  <linearGradient id="footer" x1="0" y1="0" x2="1" y2="0">', *stops(footer["stops"]),
                "  </linearGradient>"]
    out += [
        "</defs>",
        f'<rect x="0" y="0" width="{w}" height="{h}" fill="{bg.get("page", "#FFFFFF")}"/>',
        f'<path d="{band_path}" fill="url(#band)"/>',
        f'<path d="{band_path}" fill="url(#sheen)"/>',
    ]
    for key in ("bandLines", "gridLines"):
        group = bg.get(key)
        if not group:
            continue
        out.append(f'<g stroke="{group["color"]}" stroke-opacity="{num(group.get("opacity", 1))}" '
                   f'stroke-width="{num(group.get("width", 1))}" shape-rendering="crispEdges">')
        for x1, y1, x2, y2 in group["lines"]:
            out.append(f'  <line x1="{num(x1)}" y1="{num(y1)}" x2="{num(x2)}" y2="{num(y2)}"/>')
        out.append("</g>")
    if footer:
        fy = float(footer["y"])
        out.append(f'<rect x="0" y="{num(fy)}" width="{w}" height="{num(h - fy)}" fill="url(#footer)"/>')
        accent = footer.get("accent")
        if accent:
            aw = float(accent.get("width", 2))
            out.append(f'<rect x="0" y="{num(fy)}" width="{w}" height="{num(aw)}" fill="{accent["color"]}"/>')
    out.append("</svg>")
    return "\n".join(out) + "\n"


def main(argv=None) -> int:
    here = Path(__file__).resolve().parent
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--repo", type=Path, default=here.parents[1], help="repo root (default: this script's repo)")
    args = ap.parse_args(argv)
    repo = args.repo.resolve()
    layout_path = repo / "showcase" / "dashboard.json"
    layout = json.loads(layout_path.read_text(encoding="utf-8"))
    name = layout["page"].get("background") or "dashboard-background.svg"
    target = repo / "showcase" / "theme" / name
    data = render(layout).encode("utf-8")
    if target.is_file() and target.read_bytes() == data:
        print(f"unchanged: {target.relative_to(repo).as_posix()}")
        return 0
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(data)
    print(f"written: {target.relative_to(repo).as_posix()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
